# Generated by Django 3.0.7 on 2020-06-27 06:33

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('admission_year', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(2001), django.core.validators.MaxValueValidator(2020)])),
                ('telegram_username', models.CharField(max_length=32)),
                ('faculty', models.CharField(blank=True, choices=[('fit', 'Faculty Of Information Technologies'), ('fgge', 'Faculty of Geology and Geological Exploration'), ('bs', 'Business School'), ('ise', 'International School of Economics'), ('kma', 'Kazakh Maritime Academy'), ('smc', 'School of Mathematics and Cybernetics'), ('sce', 'School of Chemical Engineering')], max_length=4, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Add',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_created=True)),
                ('title', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True, max_length=250)),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('category', models.IntegerField(verbose_name=[(10, 'Lost'), (11, 'Found')])),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
