# Generated by Django 3.0.7 on 2020-07-03 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='add',
            name='category',
            field=models.IntegerField(choices=[(10, 'Lost'), (11, 'Found')]),
        ),
    ]
