# Generated by Django 3.0.7 on 2020-07-22 12:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('main', '0002_auto_20200703_0851'),
    ]

    operations = [
        migrations.AddField(
            model_name='add',
            name='views',
            field=models.IntegerField(default=0),
        ),
    ]
