# Generated by Django 3.0.7 on 2020-07-22 12:38

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('main', '0003_add_views'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='add',
            options={'ordering': ['created']},
        ),
    ]
